name: Edda CI on Push

on:
    push:
        branches: ["**"]

jobs:
    check:
        name: Check, format and lint 
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy, rustfmt

            - name: Install system dependencies
              run: |
                if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo apt-get update -y
                    sudo apt-get install -y libfontconfig1-dev pkg-config
                elif [ "$RUNNER_OS" == "macOS" ]; then
                    brew install pkg-config fontconfig
                elif [ "$RUNNER_OS" == "Windows" ]; then
                    choco install pkgconfiglite
                    choco install fontconfig
                fi
              shell: bash

            - name: Setup cache
              uses: actions/cache@v4
              with:
                  path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                  key: ${{ runner.os }}-cargo-check-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: ${{ runner.os }}-cargo-check-

            - name: Formatting
              run: cargo fmt --all --check

            - name: Linting
              run: cargo clippy --all-targets --all-features -- -D

            - name: Check
              run: cargo check --all-targets --all-features
      
    build:
        name: Build for ${{ matrix.os }}
        needs: check
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix: 
                os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
            - name: Checkout code
              uses: actions/checkout@4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy, rustfmt

            - name: Install system dependencies
              run: |
                if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo apt-get update -y
                    sudo apt-get install -y libfontconfig1-dev pkg-config
                elif [ "$RUNNER_OS" == "macOS" ]; then
                    brew install pkg-config fontconfig
                elif [ "$RUNNER_OS" == "Windows" ]; then
                    choco install pkgconfiglite
                    choco install fontconfig
                fi
              shell: bash

            - name: Setup cache
              uses: actions/cache@v4
              with:
                  path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                  key: ${{ runner.os }}-cargo-check-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: ${{ runner.os }}-cargo-check-

            - name: Build
              run: cargo build --all-targets --all-features

              





















            - name: 6-Build project
              run: cargo build 
              shell: bash

            - name: 7.0-Run root tests
              run: cargo test 
              shell: bash

            - name: 7.1-Run edda_core tests
              working-directory: ./edda_core
              run: cargo test 
              shell: bash
